#!/usr/bin/env bash
# fizzbuzz in bash

i=1

while [ $i -lt 101 ]
do
	if (( i % 5 == 0 && i % 3 == 0 ))
	then
		echo "FizzBuzz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
	else
		echo "$i"
	fi
	((i++))
done
