#!/usr/bin/env bash
# Bash script that displays "Best School" 10 times

pos_index=0

while [ $pos_index -lt 10 ]
do
	if [ $pos_index -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	((pos_index++))
done
